spring.application.name=devops
spring.datasource.url=jdbc:postgresql://localhost:5432/devops
spring.datasource.username=devops
spring.datasource.password=devops
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect